name = "OctreeBH"
uuid = "32610584-8033-4d12-ab8e-952911879412"
authors = ["Chia-Yu Hu <cyhu.astro@gmail.com> and contributors"]
version = "0.2.0"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "1.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
